@baseUrl = http://localhost:3000/api
@authToken = {{login.response.body.user.token}}

### Register user 
# @name register

POST  {{baseUrl}}/users/register
Content-Type: application/json

{
    "username": "teszt1",
    "email": "teszt@gmail.com",
    "password": "Teszt123",
    "gender": "férfi",
    "defAddress": "1000, Teszt, teszt1",
    "favCategories": "",
    "role": "user",
    "status": "active"
}

### login user
# @name login

POST  {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "teszt@gmail.com",
    "password": "Teszt123"
}

### update password
# @name password

PATCH {{baseUrl}}/users/password/57513078-9a1b-467a-b41e-96de22966e62
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "password":"Teszt123",
    "confirm":"Teszt123"
}